Issue 421 - Added OpenAPI 3.0 Artifacts, Default Swagger File Changes…
open-horizon/exchange-api pull request #422
Opened 2020-10-07 21:20 UTC by naphelps

References: #421 

Changes:
- Issue 421 - Added two OpenAPI 3.0 specification artifacts to `/doc/` project directory. One is for general users and the other is for developers.
- The Exchange's API version number is now properly specified in the default `swagger.json` file the Exchange generates.
- Corrected two test case errors in the `TestBusPolPostSearchRoute` test suite.

2020-10-07 21:21 UTC, naphelps commented
Passed all local tests.

2020-10-08 01:14 UTC, sf2ne approved these changes

2020-10-08 05:10 UTC, bmpotter requested changes

2020-10-08 05:10 UTC, bmpotter commented on src/main/scala/com/horizon/exchangeapi/SwaggerDocService.scala
> +    description = "<b>Note:</b> Test the API with curl:<br><br><code>curl -sS -u &lt;org&gt;/iamapikey:&lt;key&gt; https://&lt;host&gt;:&lt;port&gt;/&lt;edge-exchange&gt;/v1/orgs/... | jq</code></br>
I don't think it should be `<edge-exchange>`, i think it should be just `edge-exchange`, because that literal text is needed.

2020-10-08 12:26 UTC, bmpotter approved these changes

2020-10-08 12:41 UTC, merged