Issue 267 - Java 11 and SBT 1.4.0
open-horizon/exchange-api pull request #424
Opened 2020-10-08 13:50 UTC by naphelps

References: #267 

Changes:
- Issue 267 - Upgraded the Exchange to Java 11 and SBT 1.4.0. Upgraded Dockerfile to OpenJDK 11. Upgraded Travis CI specification to OpenJDK 11 and Ubuntu 20.04.

2020-10-08 13:51 UTC, naphelps commented
All local and e2e-dev tests have passed.

2020-11-09 18:08 UTC, sf2ne approved these changes

2020-11-09 19:31 UTC, bmpotter requested changes

2020-11-09 19:31 UTC, bmpotter commented on doc/openapi-3-developer.json
> +    "version" : "2.53.0"
update the version to 2.55.0

2020-11-09 19:31 UTC, bmpotter commented on doc/openapi-3-user.json
> +    "version" : "2.53.0"
update the version to 2.55.0

2020-11-09 19:59 UTC, bmpotter approved these changes

2020-11-09 20:47 UTC, merged