Update exchange resources to support secure application secrets #498
open-horizon/exchange-api pull request #502
Opened 2021-05-13 22:23 UTC by megha070

Signed-off-by: megha070 <varshney.megha070@gmail.com>
This PR addresses #491 and aims at updating exchange resources so as to support secure application secrets.

2021-05-14 16:38 UTC, naphelps requested changes

2021-05-14 16:38 UTC, naphelps commented on src/main/scala/com/horizon/exchangeapi/tables/Patterns.scala
> +final case class OneSecretBindingValue(vaultSecret: String)
Structurally `"secretBinding": [...]` is almost exactly the same as `"userInput": [...]`. Make sure the plumbing, datatypes, and Swagger examples match structurally. Under `"secrets": [...]` you are looking to store a `List[Object[String, String]]` generically speaking (Look to `OneUserInputValue` to see what is missing).

2021-05-14 16:38 UTC, naphelps commented on src/main/scala/com/horizon/exchangeapi/BusinessRoutes.scala
> +         "secrets": [
Make sure `"secrets": ...` is structurally similar to `"inputs": ...` above, but with the context of storing secrets instead of inputs.

2021-05-14 16:38 UTC, naphelps commented on src/main/scala/com/horizon/exchangeapi/BusinessRoutes.scala
> +         "secrets": [
Make sure `"secrets": ...` is structurally similar to `"inputs": ...` above, but with the context of storing secrets instead of inputs.

2021-05-14 16:38 UTC, naphelps commented on src/main/scala/com/horizon/exchangeapi/PatternsRoutes.scala
> +         "secrets": [
Make sure `"secrets": ...` is structurally similar to `"inputs": ...` above, but with the context of storing secrets instead of inputs.

2021-05-14 16:38 UTC, naphelps commented on src/main/scala/com/horizon/exchangeapi/PatternsRoutes.scala
> +         "secrets": [
Make sure `"secrets": ...` is structurally similar to `"inputs": ...` above, but with the context of storing secrets instead of inputs.

2021-05-14 16:38 UTC, naphelps commented on src/main/scala/com/horizon/exchangeapi/PatternsRoutes.scala
> +         "secrets": [
Make sure `"secrets": ...` is structurally similar to `"inputs": ...` above, but with the context of storing secrets instead of inputs.

2021-05-14 16:38 UTC, naphelps commented on src/main/scala/com/horizon/exchangeapi/tables/Schema.scala
> +      case 42 => DBIO.seq(
Can you compress your database changes into one case (case 41). See `case 40` for an example.

2021-05-14 16:38 UTC, naphelps commented on src/main/scala/com/horizon/exchangeapi/tables/Schema.scala
> +  val latestSchemaVersion = 43    // NOTE: THIS MUST BE CHANGED WHEN YOU ADD TO getUpgradeSchemaStep() above
Should be `41` with the compression request above.

2021-05-17 15:32 UTC, naphelps approved these changes

2021-05-17 15:41 UTC, sf2ne approved these changes

2021-05-17 15:41 UTC, merged