Add Exchange-API quick start document
open-horizon/exchange-api pull request #723
Opened 2024-10-22 10:15 UTC by omordyk

Add Exchange-API quick start document.
Description:
This document describes the environment and the set of steps aiming to create a local development and debugging environment.

2024-10-22 13:08 UTC, johnwalicki requested changes
Can you add ```bash to each of the markdown code blocks so that highlighting is correct for bash commands?

2024-10-22 13:08 UTC, johnwalicki commented on docs/QuickStart.md
> +```
Can you add ```bash to each of the markdown code blocks so that highlighting is correct for bash commands?

2024-10-22 13:17 UTC, johnwalicki requested changes

2024-10-22 13:17 UTC, johnwalicki commented on docs/QuickStart.md
> +
Lint warning - remove this extra line of whitespace.

2024-10-22 13:17 UTC, johnwalicki commented on docs/QuickStart.md
> +```
Lint warning - add a trailing line of whitespace

2024-10-22 13:20 UTC, johnwalicki commented
Great installation page.  If the goal will be to move this under the Open Horizon documentation website, it should complement the existing page (which has some of these instructions already)
https://open-horizon.github.io/docs/exchange-api/docs/README/

2024-10-23 11:52 UTC, omordyk commented
@johnwalicki Initial idea was to create a small guide for newcomers. I summarize my steps for preparing local development environment. If it is necessary I can move these steps in main Readme.

2024-10-23 13:26 UTC, johnwalicki approved these changes
Thanks for the lint fixes. Approved.

2024-10-23 13:37 UTC, johnwalicki commented
I like the QuickStart.md doc in your PR.  It contains additional details which are not in the main [README.md](https://github.com/open-horizon/exchange-api/blob/master/docs/README.md)  Some overlap however.

We should ask @joewxboy to also review.  We could merge these details into the README.md, accept this PR with its duplication, or split the Exchange API doc into an Installation guide (adding your details) and a Run/Tips/Docker guide.

2024-10-23 13:53 UTC, joewxboy commented
@johnwalicki and @naphelps if no objections, how about merging then polishing as a separate task?

2024-10-23 13:53 UTC, naphelps commented
No Objections.

2024-10-23 13:54 UTC, merged